name: CI - Testes e Cobertura

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/test-results/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50

      - name: Gerar Badge de Cobertura
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/test-results/jacoco/jacoco.csv
          badges-directory: .github/badges
          coverage-label: Cobertura
          generate-branches-badge: false

      - name: Commit do Badge no Repositório
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch --all
          git checkout ${{ github.head_ref }} 
          git add .github/badges

          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada no badge. Pulando commit."
            exit 0
          fi
          git commit -m "Atualizando badge de cobertura de testes"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
